
import __ASTRO_IMAGE_IMPORT_Z2lT6h7 from "./1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F1.md";
import __ASTRO_IMAGE_IMPORT_Zfei8L from "./2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F2.md";
import __ASTRO_IMAGE_IMPORT_Z288EvI from "./binocular.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2Fcontent-management.md";
import __ASTRO_IMAGE_IMPORT_1QquYz from "./3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F3.md";
import __ASTRO_IMAGE_IMPORT_Z1iVGYy from "./guidance.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2Fneed-some-help.md";
import __ASTRO_IMAGE_IMPORT_ZKJwCx from "./pacman.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2Fcontent-production.md";
import __ASTRO_IMAGE_IMPORT_SbTfd from "./building.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fbuilding-in-phone-era.md";
import __ASTRO_IMAGE_IMPORT_Z25luX1 from "./compass.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Ffrom-plan-to-working-product.md";
import __ASTRO_IMAGE_IMPORT_Z2l5vT from "./community.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2Fsocial-media-management.md";
import __ASTRO_IMAGE_IMPORT_21y3aE from "./guidance.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fcommunication-strategy.md";
import __ASTRO_IMAGE_IMPORT_BFwcr from "./spark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Ftoday-you-dont-buy-software.md";
import __ASTRO_IMAGE_IMPORT_1T0LE3 from "./scissors.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fsustainable-marketing-communication.md";
import __ASTRO_IMAGE_IMPORT_1yqaeD from "./sunrise.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fwhy-open-source.md";
export default new Map([["./1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F1.md", __ASTRO_IMAGE_IMPORT_Z2lT6h7], ["./2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F2.md", __ASTRO_IMAGE_IMPORT_Zfei8L], ["./binocular.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2Fcontent-management.md", __ASTRO_IMAGE_IMPORT_Z288EvI], ["./3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F3.md", __ASTRO_IMAGE_IMPORT_1QquYz], ["./guidance.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2Fneed-some-help.md", __ASTRO_IMAGE_IMPORT_Z1iVGYy], ["./pacman.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2Fcontent-production.md", __ASTRO_IMAGE_IMPORT_ZKJwCx], ["./building.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fbuilding-in-phone-era.md", __ASTRO_IMAGE_IMPORT_SbTfd], ["./compass.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Ffrom-plan-to-working-product.md", __ASTRO_IMAGE_IMPORT_Z25luX1], ["./community.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2Fsocial-media-management.md", __ASTRO_IMAGE_IMPORT_Z2l5vT], ["./guidance.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fcommunication-strategy.md", __ASTRO_IMAGE_IMPORT_21y3aE], ["./spark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Ftoday-you-dont-buy-software.md", __ASTRO_IMAGE_IMPORT_BFwcr], ["./scissors.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fsustainable-marketing-communication.md", __ASTRO_IMAGE_IMPORT_1T0LE3], ["./sunrise.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fwhy-open-source.md", __ASTRO_IMAGE_IMPORT_1yqaeD]]);
		