
import __ASTRO_IMAGE_IMPORT_Z2lT6h7 from "./1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F1.md";
import __ASTRO_IMAGE_IMPORT_Zfei8L from "./2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F2.md";
import __ASTRO_IMAGE_IMPORT_2cPTHw from "./spark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F3-today-you-dont-buy-software.md";
import __ASTRO_IMAGE_IMPORT_1QquYz from "./3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F3.md";
import __ASTRO_IMAGE_IMPORT_1pWiOX from "./guidance.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F2-communication-strategy.md";
import __ASTRO_IMAGE_IMPORT_sQpRw from "./scissors.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F1-sustainable-marketing-communication.md";
import __ASTRO_IMAGE_IMPORT_ZvB4WX from "./community.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2F1-content-production.md";
import __ASTRO_IMAGE_IMPORT_1fk0x from "./compass.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F4-from-plan-to-working-product.md";
import __ASTRO_IMAGE_IMPORT_1sXFDE from "./building.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F5-building-in-phone-era.md";
import __ASTRO_IMAGE_IMPORT_Z1wikjv from "./sunrise.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F6-why-open-source.md";
import __ASTRO_IMAGE_IMPORT_o3LdY from "./binocular.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2F2-social-media-management.md";
import __ASTRO_IMAGE_IMPORT_uCVOs from "./guidance.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2F4-need-some-help.md";
import __ASTRO_IMAGE_IMPORT_24akYU from "./pacman.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2F3-content-production.md";
export default new Map([["./1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F1.md", __ASTRO_IMAGE_IMPORT_Z2lT6h7], ["./2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F2.md", __ASTRO_IMAGE_IMPORT_Zfei8L], ["./spark.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F3-today-you-dont-buy-software.md", __ASTRO_IMAGE_IMPORT_2cPTHw], ["./3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2F3.md", __ASTRO_IMAGE_IMPORT_1QquYz], ["./guidance.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F2-communication-strategy.md", __ASTRO_IMAGE_IMPORT_1pWiOX], ["./scissors.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F1-sustainable-marketing-communication.md", __ASTRO_IMAGE_IMPORT_sQpRw], ["./community.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2F1-content-production.md", __ASTRO_IMAGE_IMPORT_ZvB4WX], ["./compass.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F4-from-plan-to-working-product.md", __ASTRO_IMAGE_IMPORT_1fk0x], ["./building.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F5-building-in-phone-era.md", __ASTRO_IMAGE_IMPORT_1sXFDE], ["./sunrise.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2F6-why-open-source.md", __ASTRO_IMAGE_IMPORT_Z1wikjv], ["./binocular.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2F2-social-media-management.md", __ASTRO_IMAGE_IMPORT_o3LdY], ["./guidance.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2F4-need-some-help.md", __ASTRO_IMAGE_IMPORT_uCVOs], ["./pacman.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fproduction%2F3-content-production.md", __ASTRO_IMAGE_IMPORT_24akYU]]);
		