
import __ASTRO_IMAGE_IMPORT_Z2gbYiG from "./1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2Fits-a-jungle-out-there.md";
import __ASTRO_IMAGE_IMPORT_MHMIq from "./2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2Fseriuos-help-is-needed.md";
import __ASTRO_IMAGE_IMPORT_1DKlnp from "building_for_phones.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fbuilding-for-the-phone-era.md";
import __ASTRO_IMAGE_IMPORT_ZcdFSd from "communication_strategy.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fcommunication-strategy.md";
import __ASTRO_IMAGE_IMPORT_2x2OG from "jlogo_blue_white.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Ffrom-plan-to-working-product.md";
import __ASTRO_IMAGE_IMPORT_2f90k from "open_source.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fopen-source-technology.md";
import __ASTRO_IMAGE_IMPORT_TDNMY from "./3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2Fsustainable-by-design.md";
import __ASTRO_IMAGE_IMPORT_jnPjL from "jlogo_blue_white.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fsustainable-by-design.md";
import __ASTRO_IMAGE_IMPORT_Z4WYh4 from "open_source.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Ftoday-you-dont-buy-software.md";
export default new Map([["./1.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2Fits-a-jungle-out-there.md", __ASTRO_IMAGE_IMPORT_Z2gbYiG], ["./2.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2Fseriuos-help-is-needed.md", __ASTRO_IMAGE_IMPORT_MHMIq], ["building_for_phones.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fbuilding-for-the-phone-era.md", __ASTRO_IMAGE_IMPORT_1DKlnp], ["communication_strategy.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fcommunication-strategy.md", __ASTRO_IMAGE_IMPORT_ZcdFSd], ["jlogo_blue_white.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Ffrom-plan-to-working-product.md", __ASTRO_IMAGE_IMPORT_2x2OG], ["open_source.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fopen-source-technology.md", __ASTRO_IMAGE_IMPORT_2f90k], ["./3.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fintro%2Fsustainable-by-design.md", __ASTRO_IMAGE_IMPORT_TDNMY], ["jlogo_blue_white.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Fsustainable-by-design.md", __ASTRO_IMAGE_IMPORT_jnPjL], ["open_source.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdesign%2Ftoday-you-dont-buy-software.md", __ASTRO_IMAGE_IMPORT_Z4WYh4]]);
		