
# Site settings
title: Junglestar
email: me@rokma.com
description: > # this means to ignore newlines until "baseurl:"
  From image to image form. From fantasy to fantastic. From awe to awesome. Thru media, platforms and audiences. It's a long way. We got solutions. Junglestar is a small web design boutique. Come check our Baobab tree perspective.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://junglestar.org" # the base hostname & protocol for your site
twitter_username:
github_username: toybreaker

# Build settings
#markdown: kramdown

# Filtering Content
exclude: [gulpfile.js, node_modules, package.json, icon]

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
