# The current release
version: v0.3.0

# Site settings
title: Junglestar
email: info@junglestar.org
description: "It's a jungle out there. DIY is not enough. How customers get to know you? Junglestar One Stop Shop do information architecture, screen design, deploy. We offer packed solutions all-included. Or top quality custom designs on the cheap. See our web-apps!"
baseurl: "" #"/clean" # the subpath of your site, e.g. /blog/
url: "http://junglestar.org" # the base hostname & protocol for your site
twitter_username: rokmatwit
github_username: toybreaker

# Conversion
markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
permalink: /:title/

# Exclude these files from your production _site
exclude:
 - Gemfile
 - Gemfile.lock
 - LICENSE
 - gulpfile.js
 - package.json
 - DS_Store
 - Icon
 - node_modules
 - uploads
 - rakefile

owner:
 name: Junglestar
 avatar_url: #
 email: rokmabox@gmail.com
 link: http://junglestar.org
 disqus-shortname:
 twitter: #
 facebook: #
 github: junglesta

google:
  plus: #username
  analytics: UA-49653244-1
  verify: Rt71Q1qGvbUviohh6n8KmtRoGUd-XeuuuKLBjCMvHO8

plugins:
 - html-proofer
 - jekyll-seo-tag
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-feed


#Use html-proofer with this terminal command:
# bundle exec htmlproofer ./_site --disable-external

collections:
  products:
    output: true
    permalink: /offer/:title/
  works:
    output: true
    permalink: /works/:title/
  pages:
    output: true
    permalink: /:title/
  redir:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product # change this to get the layout needed
