# The current release
version:           0.9.5

# Site settings
title:             Junglestar
email:             info@junglestar.org
description:       "It's a jungle out there. DIY is not enough. Junglestar is a small, flexible web agency. We design, code, deploy. We offer top quality solutions at resonable prices." # 160 char max
baseurl:           "" #"/clean" # the subpath of your site, e.g. /blog/
url:               "https://junglestar.org" # the base hostname & protocol for your site
twitter_username:  rokmatwit
github_username:   toybreaker

permalink:         /:title/

# Setup
sass:
  sass_dir:        _sass
  style:           :compressed
  # style:         :expanded

# Exclude these files from your production _site
exclude:
 - Gemfile
 - Gemfile.lock
 - LICENSE
 - gulpfile.js
 - package.json
 - DS_Store
 - Icon

# the following exclude is necessary to make Travis CI work:
# https://github.com/jekyll/jekyll/issues/5267
# https://github.com/jekyll/jekyll/issues/2938
# exclude:         ["vendor"]

owner:
 name:             Junglestar
 avatar_url:       #
 email:            rokmabox@gmail.com
 link:             https://junglestar.org
 disqus-shortname:
 twitter:          #
 facebook:         #
 github:           junglesta

google:
  plus:            #username
  analytics:       UA-49653244-1
  verify:          Rt71Q1qGvbUviohh6n8KmtRoGUd-XeuuuKLBjCMvHO8

plugins:
 - html-proofer
 - jekyll-seo-tag
 - jekyll-redirect-from
 - jekyll-sitemap

#Use html-proofer with this terminal command:
# bundle exec htmlproofer ./_site --check-html --disable-external --check-favicon --check-html --check-opengraph --allow-hash-href --check-sri --report_missing_doctype --report-eof-tags --report-invalid-tags --report-mismatched-tags --report-script-embeds

collections:
 offer:
  output:          true
  permalink:       /:title/
 products:
 works:
  output:          true
  permalink:       /works/:title/
 content:
 services:
  output:          true
  permalink:       /:title/
 about:
 design:


defaults:
  - scope:
      path:        ""
      type:        products
    values:
      layout:      default # change this to get the layout needed
