# Site settings
title: Junglestar
email: me@rokma.com
description: > # this means to ignore newlines until "baseurl:"
  It's a jungle out there. DIY is not enough. How customers get to know you?
baseurl: "" #"/clean" # the subpath of your site, e.g. /blog/
url: "http://junglestar.org" # the base hostname & protocol for your site
twitter_username: rokmatwit
github_username:  toybreaker

# Build settings
markdown: kramdown
