- name: custom design
  layout: product
  title: amazing custom design
  product_group: design
  description: "Junglestar, a small, flexible, One Stop Shop web agency. We do information architecture, screen design, deploy. Packed solutions all-included. Or top quality custom designs on the cheap. We help companies and individuals organize their communication. We grow relationships with clients.
We design, produce & develop well thought user experiences. From [slide shows](http://revealing.junglestar.org/#/8/1) to [offline ready web apps]"
  permalink: /offer/custom-design/
  question: But I want this that and also...
  products:
    product_name: "Custom designs"
    product_subname: "Top quality custom designs at competitive prices."
    product_desc: "We grow relationships with clients.
  We design, produce & develop well thought user experiences. Working with your ideas and your existing team."
    product_selling_points: [All the components in other offers, We do information architecture screen-design deploy, We grow relationships, SSL/CDN global coverage, Social media friendly, With Your-Company-Feel build into it for you!]
- name: one pager
  layout: product
  title: amazing one pager
  product_group: design
  description: "Junglestar, a small, flexible, One Stop Shop web agency. We do information architecture, screen design, deploy. Packed solutions all-included. Or top quality custom designs on the cheap. We help companies and individuals organize their communication. We grow relationships with clients.
  We design, produce & develop well thought user experiences. From [slide shows](http://revealing.junglestar.org/#/8/1) to [offline ready web apps]"
  permalink: /offer/one-pager/
  question: Need website. How much?
  products:
    product_name: "Packed solutions all-included"
    product_subname: "Quality websites templates. All included."
    product_desc: "We load data, process everything and produce a creamy website ready to compete."
    product_selling_points: [Responsive design, SEO optimized, Secured https included, CDN global coverage, Social media friendly]
- name: full site
  layout: product
  title: amazing full site
  product_group: design
  description: "Junglestar, a small, flexible, One Stop Shop web agency. We do information architecture, screen design, deploy. Packed solutions all-included. Or top quality custom designs on the cheap. We help companies and individuals organize their communication. We grow relationships with clients.
  We design, produce & develop well thought user experiences. From [slide shows](http://revealing.junglestar.org/#/8/1) to [offline ready web apps]"
  permalink: /offer/full-site/
  question: Need a site and I have questions...
  products:
    product_name: "Packed solutions all-included"
    product_subname: "Quality websites templates. All included."
    product_desc: "We load data, process everything and produce a creamy website ready to compete."
    product_selling_points: [Responsive design, SEO optimized, Secured https included, CDN global coverage, Social media friendly]
